export const refs = {
  artistsListContainer: document.querySelector('.artists-list'),
  loadMoreBtn: document.querySelector('.load-more-btn'),
  loader: document.querySelector('.loader'),
  artistDetailsModal: document.querySelector('.js-artist-details-backdrop'),
  artistDetailsContainer: document.querySelector('.artist-modal-content'),
  feedbacksContainer: document.querySelector('.swiper-wrapper'),
  paginationDotFirst: document.querySelector('.dot-first'),
  paginationDotMiddle: document.querySelector('.dot-middle'),
  paginationDotLast: document.querySelector('.dot-last'),
  modalLoader: document.querySelector('.modal-loader-wrapper .loader'),
  artistModal: document.querySelector('.artist-modal'),
  genreList: document.querySelector('.genre-list'),

  mobileMenuOpenBtn: document.querySelector('.mobile-menu-open-btn'),
  mobileMenuCloseBtn: document.querySelector('.mobile-menu-close-btn'),
  mobileMenu: document.querySelector('.mobile-menu'),
  mobileMenuLinks: document.querySelectorAll('.mobile-menu-link'),
  filtersToggle: document.querySelector('.filters-toggle'),
  filtersMenu: document.querySelector('.filters-menu'),
  filtersPanel: document.querySelector('.filters-panel'),
};
